@startuml
class BackupJob {
    + BackupJob(backup:Backup, repository:IRepository, jobObjects:List<JobObject>, restorePointCreationalAlgorithm:IRestorePointCreationalAlgorithm)
    + BackupJob(backup:Backup, repository:IRepository, restorePointCreationalAlgorithm:IRestorePointCreationalAlgorithm)
    + AddObject(jobObject:JobObject)
    + RemoveObject(jobObject:JobObject)
    + CreateRestorePoint()
}
BackupJob o-- Backup
BackupJob o-- "0..n" JobObject
BackupJob o-- IRestorePointCreationalAlgorithm
BackupJob o-- IRepository

@enduml
