@startuml
class TcpFileTransferClient {
    + TcpFileTransferClient(address:string, port:ushort)
    + Dispose()
    + SendFiles(files:IReadOnlyList<TransferFile>, folderName:string)
    - SendSingleFile(file:TransferFile)
    -Start()
    Close()
    - _client : TcpClient
    - _address : string 
    - _port : ushort 
    - _stm : Stream?
}
@enduml
