@startuml
class FileHeader {
    + FileHeader(name:string, size:int)
    + FileHeader(bytes:byte[])
    + GetByteHeader() : byte[]
    + GetName() : string
    + GetSize() : int
    - _size : byte[]
    - _nameSize : byte[]
    - _name : byte[]
}
@enduml
