@startuml
package Backups{
    !include ./Backups/Repositories/LocalFSRepository.puml
    !include ./Backups/Repositories/TcpRepository.puml
    !include ./Backups/Repositories/IRepository.puml
    !include ./Backups/CompressionAlgorithms/ZipCompressor.puml
    !include ./Backups/CompressionAlgorithms/ICompressor.puml
    !include ./Backups/CreationalAlgorithms/SingleStorageRestorePointCreationalAlgorithm.puml
    !include ./Backups/CreationalAlgorithms/SplitStorageRestorePointCreationalAlgorithm.puml
    !include ./Backups/CreationalAlgorithms/IRestorePointCreationalAlgorithm.puml
    !include ./Backups/Entities/BackupJob.puml
    !include ./Backups/Entities/Backup.puml
    !include ./Backups/Entities/JobObject.puml
    !include ./Backups/Entities/Storage.puml
    !include ./Backups/Entities/RestorePoint.puml
}
package Client{
    !include ./Backups.Client/TcpFileTransferClient.puml
}

package Server{
    !include ./Backups.Server/TcpServer.puml
    !include ./Backups.Server/Repositories/LocalFSRepository.puml
    !include ./Backups.Server/Repositories/IServerRepository.puml
}

package NetworkTransfer{
    !include ./Backups.NetworkTransfer/Headers/FileHeader.puml
    !include ./Backups.NetworkTransfer/Headers/FolderHeader.puml
    !include ./Backups.NetworkTransfer/Entities/TransferFile.puml
}



@enduml