@startuml
class MultipleFileRestorePointCreationalAlgorithm {
    + Run(objects:List<JobObject>, repository:IRepository) : RestorePoint
}
IRestorePointCreationalAlgorithm <|-- MultipleFileRestorePointCreationalAlgorithm
@enduml
