@startuml
class SingleFileRestorePointCreationalAlgorithm {
    + Run(objects:List<JobObject>, repository:IRepository) : RestorePoint
}
IRestorePointCreationalAlgorithm <|-- SingleFileRestorePointCreationalAlgorithm
@enduml
